### PR TITLE
Sprint 1 Backend API Documentation (#25)

### PR DESCRIPTION
**Pull request by preyansh98**
## Description

Completed API Documentation for the following routes: 
```
[ { path: '/delivery', methods: [ 'GET' ] },
{ path: '/delivery/issue', methods: [ 'POST', 'PUT' ] },
{ path: '/campus', methods: [ 'GET' ] },
{ path: '/campus/issue', methods: [ 'POST', 'DELETE', 'PUT' ] },
{ path: '/user', methods: [ 'GET' ] },
{ path: '/user/login', methods: [ 'GET' ] },
{ path: '/user/signup', methods: [ 'POST' ] } ]

```
## Related Issue

Addresses Issue #25 

## How Has This Been Tested

Locally verified output of API Docs on localhost:5000/api-docs

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by 20001LastOrder** [comment]
Just a notice that we will have multiple user types, so either we have separate login/signup routers for each type or we should pass the user type as a parameter of the request. (I prefer latter)

**Comment by 20001LastOrder** [comment]
Also the backend app was originally developed for another app, so the router paths are not final. So feel free to document or remove any new router path that you feel we may need.

**Comment by preyansh98** [comment]
Hi @20001LastOrder, good point! 

Just so we don't have a mismatch between the documentation and the deployed backend code, I think all future PR's that modify the backend routes should accompany the corresponding documentation change. 

Maybe the scrum masters can help us in enforcing this?

**Comment by chrisliii** [comment]
I can check each pull request to make sure the documentation is updated accordingly.

**Pull request merged**
