### PR TITLE
implement order status update api

### PR DESCRIPTION
**Pull request by Catosine**
## Description

Implemented the order status update API

## Related Issue
#111 

## How Has This Been Tested
Implement with [unit test](https://github.com/20001LastOrder/McGrill_App/blob/pengnanf/backend/tests/order_test.js)
Successful with local test

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Catosine** [comment]
> Please write some unit tests for the APIs.
> You can find out how to write tests in the Wiki.
> Thanks

Test implemented.
Please see [here](https://github.com/20001LastOrder/McGrill_App/blob/pengnanf/backend/tests/order_test.js)

**Comment by 20001LastOrder** [comment]
No luck sadly... I need to try to fix the master fail first and then I'll probably come back to this. At the meantime, it will be great if you can take a look of it :)

**Comment by 20001LastOrder** [comment]
Merge master again should solve the failure (hopefully)

**Comment by Catosine** [comment]
> Merge master again should solve the failure (hopefully)

Thanks.

**Comment by 20001LastOrder** [comment]
YEAHHHHHHHHH

**Pull request merged**
